import { z } from "zod";
import { candidatesFor } from "./catalog";
import {
  DEFAULT_THRESHOLD,
  KEY_ERROR_MESSAGE,
  UI_ORDER,
  UI_WIDGET,
  X_ACCEPT,
  X_MAX_SIZE_MB,
  X_MULTIPLE,
  X_PREFIX,
  X_SUFFIX,
  X_THRESHOLD,
  X_ZOD,
  clamp01,
  normalizeField,
  normalizeForm,
  type SavedForm,
} from "./form-json";
import { TIME_PATTERN, buildSchema, defaultMessage } from "./schema";
import type { FieldSpec } from "./types";

/**
 * Paste-to-form conversion, and the builder's own file format.
 *
 * The document is JSON Schema draft 2020-12 plus an RJSF-style uiSchema, and the
 * same one is used in a downloaded file, in the URL hash and in localStorage:
 *
 *   { "schema": { "type": "object", "properties": { … } }, "uiSchema": { … } }
 *
 * The schema is **generated by Zod**, not written by hand: `shared/schema.ts`
 * builds the very schema the preview validates with, carrying the builder's
 * settings as `.meta()` — purpose as the object's `description`, label/hint as a
 * field's `title`/`description`, and the settings JSON Schema has no place for as
 * `x-` extensions (`x-threshold`, `x-prefix`, `x-suffix`, `x-accept`,
 * `x-maxSizeMb`, `x-multiple`). `formDocument` then calls `z.toJSONSchema` and
 * repairs the few shapes Zod cannot express (`fixShapes`). The uiSchema is the
 * only hand-built object, and it is not JSON Schema: `ui:widget` and `ui:order`.
 *
 * Reading is lenient and hand-written — Zod cannot produce a `FieldSpec`. Any
 * JSON Schema object works, and everything the builder cannot express becomes a
 * text field with an entry in `warnings`.
 */

export type FormDocument = { schema: Record<string, unknown>; uiSchema: Record<string, unknown> };

export type ImportFormat = "builder-file" | "json-schema" | "zod";

export type ImportResult = {
  ok: boolean;
  format: ImportFormat;
  purpose: string;
  fields: FieldSpec[];
  /** Builder files only, and only when the file carries it. */
  threshold?: number;
  overrides?: Record<string, string>;
  warnings: string[];
};

type Json = Record<string, unknown>;

const isObj = (v: unknown): v is Json => !!v && typeof v === "object" && !Array.isArray(v);
const finite = (v: unknown) => (typeof v === "number" && Number.isFinite(v) ? v : undefined);
const asText = (v: unknown) => (typeof v === "string" ? v : JSON.stringify(v));

/** `full_name` / `fullName` → `Full name`, the label used when the schema has no title. */
function prettify(key: string): string {
  const words = key
    .replace(/[_\-.]+/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .trim();
  return words ? words[0].toUpperCase() + words.slice(1) : key;
}

/* ------------------------------------------------------------------ writing */

export function formDocument(s: SavedForm): FormDocument {
  const form = normalizeForm(s);
  const byName: Record<string, FieldSpec | undefined> = Object.fromEntries(form.fields.map((f) => [f.name, f]));
  const schema = z.toJSONSchema(buildSchema(form.fields, { purpose: form.purpose, threshold: form.threshold }), {
    // `draft-2020-12` is what the builder's own documents declare; "any" turns
    // the bits Zod cannot express (z.date(), fully covered by `fixShapes`) into
    // `{}` instead of throwing, so one odd field never blocks an export.
    target: "draft-2020-12",
    unrepresentable: "any",
    override: ({ jsonSchema, path }) => fixShapes(jsonSchema, path, byName, form),
  });
  const uiSchema: Json = {};
  for (const f of form.fields) if (form.overrides[f.id]) uiSchema[f.name] = { [UI_WIDGET]: form.overrides[f.id] };
  uiSchema[UI_ORDER] = form.fields.map((f) => f.name);
  return { schema, uiSchema };
}

/**
 * The JSON Schema `z.toJSONSchema` cannot produce on its own. Every branch here
 * repairs a node Zod already generated — there is no second serializer:
 *
 *   date / date-range   z.date() has no JSON Schema form (`{}`)          → format: date
 *   time                only a regex pattern survived                    → format: time, pattern dropped
 *   required boolean    the `.refine(v => v)` "must be ticked" is lost   → const: true
 *   range               the tuple's bounds live in `.refine`             → minimum/maximum on prefixItems
 *   file                the size limit became a byte `maxLength`         → dropped, x-maxSizeMb carries it
 *   email               Zod also emits a long regex                      → pattern dropped
 *   required string     Zod always emits minLength: 1                    → dropped unless the field sets a minimum
 *   required            Zod keeps empty-allowed strings in `required`    → exactly the builder's required fields
 */
function fixShapes(node: Json, path: (string | number)[], byName: Record<string, FieldSpec | undefined>, form: SavedForm): void {
  if (!path.length) {
    const required = form.fields.filter((f) => f.required).map((f) => f.name);
    if (required.length) node.required = required;
    else delete node.required;
    return;
  }
  if (path[0] !== "properties") return;
  const f = byName[String(path[1])];
  if (!f) return;
  const nested = path.length > 2; // a node inside the field, e.g. a date range's from/to
  // A branch that only allows "empty" (`const: ""`) is not the field itself.
  if (nested && node.const !== undefined) return;
  // Zod keys its enum output by value, so options like "0" would come first; the builder's order wins.
  if (Array.isArray(node.enum) && f.options?.length) node.enum = [...f.options];

  switch (f.kind) {
    case "date":
      // A union node is only a wrapper; the branch inside carries the type.
      if (!Array.isArray(node.anyOf)) {
        node.type = "string";
        node.format = "date";
      }
      break;
    case "date-range":
      if (nested) {
        node.type = "string";
        node.format = "date";
      }
      break;
    case "time":
      if (!Array.isArray(node.anyOf)) {
        node.type = "string";
        node.format = "time";
        delete node.pattern;
      }
      break;
    case "string":
      // Zod also emits a long regex for format: email; it adds nothing to the meaning.
      if (node.format === "email") delete node.pattern;
      // Zod always emits minLength: 1 for a required string; the builder's "required" covers that.
      if (!nested && !node.format && !Array.isArray(node.anyOf) && f.required && (f.min == null || f.min < 1) && node.minLength === 1) delete node.minLength;
      break;
    case "boolean":
      if (!nested && f.required) node.const = true;
      break;
    case "range":
      if (!nested && Array.isArray(node.prefixItems)) {
        const [first, second] = node.prefixItems;
        if (isObj(first) && f.min != null) first.minimum = f.min;
        if (isObj(second) && f.max != null) second.maximum = f.max;
      }
      break;
    case "file":
      delete node.maxLength; // bytes; the builder stores megabytes as x-maxSizeMb
      break;
  }
}

export const formToJson = (s: SavedForm) => JSON.stringify(formDocument(s), null, 2);

/* ------------------------------------------------------------------ reading */

type ReadSchema = {
  ok: boolean;
  purpose: string;
  fields: FieldSpec[];
  threshold?: number;
  overrides: Record<string, string>;
  warnings: string[];
};

function readSchema(schema: Json, uiSchema: Json): ReadSchema {
  const warnings: string[] = [];
  const out: ReadSchema = { ok: false, purpose: "", fields: [], overrides: {}, warnings };
  // Zod's own compiler is the cheapest validity check: it rejects contradictory
  // or malformed schemas, and its complaint is useful to show. Best effort only —
  // the mapping below still runs, so a compile failure never blocks an import.
  try {
    const compilable = schema as Parameters<typeof z.fromJSONSchema>[0]; // the same document, parsed from JSON
    z.fromJSONSchema(compilable);
  } catch (e) {
    warnings.push(`Zod cannot compile this schema: ${(e as Error).message.split("\n")[0]}`);
  }
  if (!isObj(schema.properties)) {
    warnings.push('No "properties" found. Paste an object schema, e.g. {"type":"object","properties":{…}}.');
    return out;
  }
  const props = schema.properties;
  const requiredNames = Array.isArray(schema.required) ? schema.required.filter((n): n is string => typeof n === "string") : [];
  out.fields = Object.entries(props).map(([name, prop], i) => normalizeField(mapProperty(name, isObj(prop) ? prop : {}, requiredNames.includes(name), i, warnings)));
  for (const name of requiredNames) if (!(name in props)) warnings.push(`"required" lists "${name}", which is not in properties.`);
  // Ids follow the order the fields are shown in, so a restored form looks like the original.
  out.fields = applyOrder(out.fields, uiSchema[UI_ORDER], warnings).map((f, i) => ({ ...f, id: `imp_${i + 1}` }));
  out.overrides = readOverrides(uiSchema, out.fields, warnings);
  if (!out.fields.length) warnings.push('The "properties" map is empty.');
  out.purpose = typeof schema.description === "string" ? schema.description : typeof schema.title === "string" ? schema.title : "";
  const threshold = finite(schema[X_THRESHOLD]);
  if (threshold !== undefined) out.threshold = clamp01(threshold);
  out.ok = out.fields.length > 0;
  return out;
}

/**
 * One JSON Schema property → a field. KINDS: add new kinds here (time, date-range, range, file).
 * Everything the builder writes is understood, plus the general JSON Schema around it.
 */
function mapProperty(name: string, raw: Json, required: boolean, i: number, warnings: string[]): FieldSpec {
  const { schema: s, emptyAllowed } = unwrapAnyOf(raw, name, warnings);
  // `"type": ["string", "null"]` means the value can be absent.
  const nullable = Array.isArray(s.type) ? s.type.includes("null") : s.type === "null";
  const type = Array.isArray(s.type) ? s.type.find((t) => t !== "null") : s.type;
  const f: FieldSpec = {
    id: `imp_${i + 1}`,
    name,
    // A title is the label, exactly as written; without one, the key is prettified.
    label: typeof s.title === "string" ? s.title : prettify(name),
    kind: "string",
    required: required && !nullable && !emptyAllowed,
  };
  if (typeof s.description === "string" && s.description) f.description = s.description;
  // Verbatim custom Zod code (`x-zod`) and hand-written messages (`errorMessage`) are text we carry along.
  if (typeof s[X_ZOD] === "string" && s[X_ZOD].trim()) f.customZod = s[X_ZOD];
  const messages = readErrorMessages(s.errorMessage);
  if (messages) f.errorMessage = messages;

  // `enum` wins over `type`: JSON Schema writes either, or both.
  if (Array.isArray(s.enum)) {
    if (!s.enum.length) {
      warnings.push(`${name}: the enum is empty — used a text field.`);
      return f;
    }
    f.kind = "enum";
    f.options = s.enum.map(asText);
    if (!s.enum.every((v) => typeof v === "string")) warnings.push(`${name}: non-text enum values were turned into text.`);
    return f;
  }
  if (s.const !== undefined) {
    // `const: true` is how a required boolean ("must be ticked") survives JSON Schema.
    if (typeof s.const === "boolean") {
      f.kind = "boolean";
      if (s.const) f.required = true;
      return f;
    }
    f.kind = "enum";
    f.options = [asText(s.const)];
    return f;
  }

  switch (type) {
    case "string": {
      const format = typeof s.format === "string" ? s.format : undefined;
      if (format === "date" || format === "date-time") {
        f.kind = "date";
        if (format === "date-time") warnings.push(`${name}: date-time is treated as a date (the time is dropped).`);
        if (finite(s.minLength) !== undefined || finite(s.maxLength) !== undefined) warnings.push(`${name}: minLength/maxLength are ignored on a date field.`);
      } else if (format === "time") {
        f.kind = "time";
        if (finite(s.minLength) !== undefined || finite(s.maxLength) !== undefined) warnings.push(`${name}: minLength/maxLength are ignored on a time field.`);
      } else if (format === "binary" || format === "byte" || s.contentEncoding === "binary") {
        f.kind = "file";
        readFileSettings(s, f, name, warnings);
      } else {
        if (format === "email") f.format = "email";
        else if (format === "uri" || format === "url") f.format = "url";
        else if (format) warnings.push(`${name}: format "${format}" is not supported — plain text.`);
        f.min = finite(s.minLength);
        f.max = finite(s.maxLength);
        if (typeof s[X_PREFIX] === "string" && s[X_PREFIX]) f.prefix = s[X_PREFIX];
        if (typeof s[X_SUFFIX] === "string" && s[X_SUFFIX]) f.suffix = s[X_SUFFIX];
      }
      break;
    }
    case "number":
    case "integer": {
      f.kind = "number";
      f.min = finite(s.minimum);
      f.max = finite(s.maximum);
      if (f.min === undefined && finite(s.exclusiveMinimum) !== undefined) {
        f.min = finite(s.exclusiveMinimum);
        warnings.push(`${name}: exclusiveMinimum is treated as the minimum.`);
      }
      if (f.max === undefined && finite(s.exclusiveMaximum) !== undefined) {
        f.max = finite(s.exclusiveMaximum);
        warnings.push(`${name}: exclusiveMaximum is treated as the maximum.`);
      }
      break;
    }
    case "boolean":
      f.kind = "boolean";
      break;
    case "array": {
      const items = isObj(s.items) ? s.items : {};
      const [first, second] = Array.isArray(s.prefixItems) ? s.prefixItems : [];
      if (isObj(first) && isObj(second) && isNumberNode(first) && isNumberNode(second)) {
        // A z.tuple of two numbers: the builder's range, each end's bound on its own item.
        f.kind = "range";
        f.min = finite(first.minimum);
        f.max = finite(second.maximum);
        rangeLengthWarning(name, s, warnings);
      } else if (items.format === "binary" || items.contentEncoding === "binary") {
        f.kind = "file";
        f.multiple = true;
        readFileSettings(s, f, name, warnings);
        readFileSettings(items, f, name, warnings);
        const minItems = finite(s.minItems);
        if (minItems !== undefined && !(minItems === 1 && f.required)) warnings.push(`${name}: minItems cannot be expressed in the builder — ignored.`);
      } else if (Array.isArray(items.enum) && items.enum.length) {
        f.kind = "multi";
        f.options = items.enum.map(asText);
        if (!items.enum.every((v) => typeof v === "string")) warnings.push(`${name}: non-text options were turned into text.`);
        // "at least one when required" is how the builder writes it; anything else is lost.
        const minItems = finite(s.minItems);
        if ((minItems !== undefined || finite(s.maxItems) !== undefined) && !(minItems === 1 && f.required)) {
          warnings.push(`${name}: minItems/maxItems cannot be expressed in the builder — ignored.`);
        }
      } else if (isNumberNode(items)) {
        // The older shape: one item schema for both numbers, carrying both bounds.
        f.kind = "range";
        f.min = finite(items.minimum);
        f.max = finite(items.maximum);
        rangeLengthWarning(name, s, warnings);
      } else {
        warnings.push(`${name}: a list without a fixed set of options — used a text field.`);
      }
      break;
    }
    case "object": {
      // Zod writes a date range as a plain object of two dates; older files also marked it with `format`.
      const props = isObj(s.properties) ? s.properties : {};
      if (s.format === "date-range" || (isDateNode(props.from) && isDateNode(props.to))) {
        f.kind = "date-range";
        for (const key of ["from", "to"] as const) {
          if (!isDateNode(props[key])) warnings.push(`${name}: the date range has no "${key}" date.`);
        }
      } else {
        warnings.push(`${name}: type "object" is not supported — used a text field.`);
      }
      break;
    }
    case undefined:
      warnings.push(`${name}: no "type" and no "enum" — used a text field.`);
      break;
    default:
      warnings.push(`${name}: type "${String(type)}" is not supported — used a text field.`);
  }

  if (f.kind !== "date-range" && (s.$ref || s.oneOf || s.anyOf || s.allOf || s.not || isObj(s.properties))) {
    warnings.push(`${name}: nested or composed schemas ($ref/oneOf/anyOf/allOf) are not resolved.`);
  }
  return f;
}

/**
 * `anyOf [<type>, { const: "" }]` (or a `null` branch) is how Zod writes a text
 * field that may be left empty; the value type is the other branch.
 */
function unwrapAnyOf(s: Json, name: string, warnings: string[]): { schema: Json; emptyAllowed: boolean } {
  const branches = Array.isArray(s.anyOf) ? s.anyOf.filter(isObj) : [];
  if (!branches.length) return { schema: s, emptyAllowed: false };
  const isEmpty = (b: Json) => b.const === "" || b.const === null || b.type === "null";
  const rest = branches.filter((b) => !isEmpty(b));
  const emptyAllowed = rest.length !== branches.length;
  if (rest.length > 1) {
    warnings.push(`${name}: anyOf with ${rest.length} alternatives is not supported — used a text field.`);
    return { schema: s, emptyAllowed };
  }
  if (!rest.length) {
    warnings.push(`${name}: anyOf holds no value type — used a text field.`);
    return { schema: s, emptyAllowed };
  }
  const merged: Json = { ...s, ...rest[0] };
  delete merged.anyOf;
  return { schema: merged, emptyAllowed };
}

/** File settings: the builder's own `x-` keys, with a byte `maxLength` as a fallback for other files. */
function readFileSettings(node: Json, f: FieldSpec, name: string, warnings: string[]): void {
  if (typeof node[X_ACCEPT] === "string" && node[X_ACCEPT]) f.accept = node[X_ACCEPT];
  const mb = finite(node[X_MAX_SIZE_MB]);
  if (mb !== undefined) {
    f.maxSizeMb = mb;
  } else {
    const bytes = finite(node.maxLength);
    if (bytes !== undefined) {
      const size = Math.round((bytes / (1024 * 1024)) * 100) / 100;
      if (size >= 0.1 && Math.round(size * 1024 * 1024) === bytes) f.maxSizeMb = size;
      else warnings.push(`${name}: maxLength ${bytes} is not a size in megabytes — ignored.`);
    }
  }
  if (typeof node[X_MULTIPLE] === "boolean") f.multiple = node[X_MULTIPLE];
}

/** The `errorMessage` keyword: ajv-errors keeps the keyword keys, a bare string is the required message. */
function readErrorMessages(v: unknown): Record<string, string> | undefined {
  if (typeof v === "string") return v ? { type: v } : undefined;
  if (!isObj(v)) return undefined;
  const out: Record<string, string> = {};
  for (const [keyword, message] of Object.entries(v)) if (typeof message === "string" && message) out[keyword] = message;
  return Object.keys(out).length ? out : undefined;
}

/** A range is exactly two numbers; any other length cannot be expressed in the builder. */
function rangeLengthWarning(name: string, s: Json, warnings: string[]): void {
  const minItems = finite(s.minItems);
  const maxItems = finite(s.maxItems);
  if (minItems !== undefined && minItems !== 2) warnings.push(`${name}: only a two-number range is supported — minItems is ignored.`);
  if (maxItems !== undefined && maxItems !== 2) warnings.push(`${name}: only a two-number range is supported — maxItems is ignored.`);
}

function isNumberNode(n: Json): boolean {
  return n.type === "number" || n.type === "integer";
}

function isDateNode(n: unknown): boolean {
  return isObj(n) && n.type === "string" && (n.format === "date" || n.format === "date-time");
}

/** `ui:order` decides the field order; names missing from it keep their schema order. */
function applyOrder(fields: FieldSpec[], order: unknown, warnings: string[]): FieldSpec[] {
  if (!Array.isArray(order)) return fields;
  const rest: Record<string, FieldSpec> = Object.fromEntries(fields.map((f) => [f.name, f]));
  const ordered: FieldSpec[] = [];
  for (const name of order) {
    if (typeof name !== "string") continue;
    const f = rest[name];
    if (!f) {
      warnings.push(`ui:order lists "${name}", which is not a field.`);
      continue;
    }
    ordered.push(f);
    delete rest[name];
  }
  return [...ordered, ...Object.values(rest)];
}

/** `ui:widget` per field → the builder's override map, keyed by the regenerated field ids. */
function readOverrides(uiSchema: Json, fields: FieldSpec[], warnings: string[]): Record<string, string> {
  const byName: Record<string, FieldSpec> = Object.fromEntries(fields.map((f) => [f.name, f]));
  const out: Record<string, string> = {};
  for (const [name, entry] of Object.entries(uiSchema)) {
    if (name === UI_ORDER) continue;
    const widget = isObj(entry) && typeof entry[UI_WIDGET] === "string" ? entry[UI_WIDGET] : undefined;
    if (!widget) continue;
    const f = byName[name];
    if (!f) {
      warnings.push(`ui:widget is set for "${name}", which is not a field.`);
      continue;
    }
    if (!candidatesFor(f.kind).some((c) => c.id === widget)) {
      warnings.push(`"${name}": ui:widget "${widget}" cannot hold a ${f.kind} value — ignored.`);
      continue;
    }
    out[f.id] = widget;
  }
  return out;
}

/* ------------------------------------------------------------------ Zod source */

const ZOD_HINT = "Paste Zod source containing a z.object({ … }) literal.";

const SIMPLE_ESCAPES: Record<string, string> = { n: "\n", t: "\t", r: "\r", b: "\b", f: "\f", v: "\v", "0": "\0" };

function unescapeLiteral(lit: string): string {
  return lit
    .slice(1, -1)
    .replace(/\\(u[0-9a-fA-F]{4}|x[0-9a-fA-F]{2}|[\s\S])/g, (_, esc: string) =>
      esc.length > 1 ? String.fromCharCode(parseInt(esc.slice(1), 16)) : (SIMPLE_ESCAPES[esc] ?? esc),
    );
}

/** The quoted literal that starts at `i`, escapes included. Comments are already stripped. */
function readStringAt(src: string, i: number): string {
  const quote = src[i];
  let out = quote;
  for (let j = i + 1; j < src.length; j++) {
    out += src[j];
    if (src[j] === "\\") {
      out += src[++j] ?? "";
      continue;
    }
    if (src[j] === quote) break;
  }
  return out;
}

function stripComments(src: string): string {
  let out = "";
  for (let i = 0; i < src.length; ) {
    const c = src[i];
    if (c === '"' || c === "'" || c === "`") {
      const lit = readStringAt(src, i);
      out += lit;
      i += lit.length;
      continue;
    }
    if (c === "/" && src[i + 1] === "/") {
      while (i < src.length && src[i] !== "\n") i++;
      continue;
    }
    if (c === "/" && src[i + 1] === "*") {
      i += 2;
      while (i < src.length && !(src[i] === "*" && src[i + 1] === "/")) i++;
      i += 2;
      continue;
    }
    out += c;
    i++;
  }
  return out;
}

/** Index of the `}` matching the `{` at `open`, or -1. */
function matchBrace(src: string, open: number): number {
  return matchDelimiter(src, open, "{", "}");
}

/** Index of the delimiter matching the opening one at `open`, or -1. Ignores strings. */
function matchDelimiter(src: string, open: number, openCh: string, closeCh: string): number {
  let depth = 0;
  for (let i = open; i < src.length; ) {
    const c = src[i];
    if (c === '"' || c === "'" || c === "`") {
      const lit = readStringAt(src, i);
      i += lit.length;
      continue;
    }
    if (c === openCh) depth++;
    else if (c === closeCh && --depth === 0) return i;
    i++;
  }
  return -1;
}

/** Splits an object body on commas at depth 0, and on newlines that are not a `.method(…)` continuation. */
function splitEntries(body: string): string[] {
  const out: string[] = [];
  const open: string[] = [];
  let buf = "";
  for (let i = 0; i < body.length; ) {
    const c = body[i];
    if (c === '"' || c === "'" || c === "`") {
      const lit = readStringAt(body, i);
      buf += lit;
      i += lit.length;
      continue;
    }
    if (c === "{" || c === "(" || c === "[") open.push(c);
    else if (c === "}" || c === ")" || c === "]") open.pop();
    else if (!open.length && (c === "," || c === "\n")) {
      const rest = body.slice(i + 1);
      if (c === "\n" && rest.trimStart().startsWith(".")) {
        buf += c;
        i++;
        continue;
      }
      out.push(buf);
      buf = "";
      i++;
      continue;
    }
    buf += c;
    i++;
  }
  out.push(buf);
  return out.map((e) => e.trim()).filter(Boolean);
}

/** Index of `ch` at depth 0, or -1. */
function indexOfTopLevel(text: string, ch: string): number {
  const open: string[] = [];
  for (let i = 0; i < text.length; ) {
    const c = text[i];
    if (c === '"' || c === "'" || c === "`") {
      const lit = readStringAt(text, i);
      i += lit.length;
      continue;
    }
    if (c === "{" || c === "(" || c === "[") open.push(c);
    else if (c === "}" || c === ")" || c === "]") open.pop();
    else if (!open.length && c === ch) return i;
    i++;
  }
  return -1;
}

const DESCRIBE_RE = /\.\s*describe\s*\(\s*("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`)\s*\)/;

/** The first `.describe("…")` string in an expression, if any. */
function matchDescribe(expr: string): string | undefined {
  const m = DESCRIBE_RE.exec(expr);
  return m ? unescapeLiteral(m[1]) : undefined;
}

/** The string options of the first `z.enum([ … ])` in the expression, or null. */
function zodEnumOptions(expr: string): string[] | null {
  const at = expr.search(/z\s*\.\s*enum\s*\(/);
  if (at < 0) return null;
  const open = expr.indexOf("[", at);
  if (open < 0) return null;
  const options: string[] = [];
  for (let i = open + 1; i < expr.length; ) {
    const c = expr[i];
    if (c === "]") break;
    if (c === '"' || c === "'" || c === "`") {
      const lit = readStringAt(expr, i);
      options.push(unescapeLiteral(lit));
      i += lit.length;
      continue;
    }
    i++;
  }
  return options.length ? options : null;
}

const ZOD_OPTIONAL_RE = /\.\s*optional\s*\(\s*\)|\.\s*nullable\s*\(\s*\)|\.\s*or\s*\(\s*z\s*\.\s*literal\s*\(\s*(?:""|''|``)\s*\)\s*\)/;

// The base type is what the expression *starts* with; a later `.url()` or
// `.or(z.literal(""))` only tunes it, so these must stay anchored.
// KINDS: add new kinds here (time, date-range, range, file).
const ZOD_ARRAY = /^z\s*\.\s*array\s*\(/;
const ZOD_ENUM = /^z\s*\.\s*enum\s*\(/;
const ZOD_LITERAL = /^z\s*\.\s*literal\s*\(\s*("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`)\s*\)/;
const ZOD_STRING = /^z\s*\.\s*(?:string|coerce\s*\.\s*string)\s*\(/;
const ZOD_EMAIL = /^z\s*\.\s*email\s*\(/;
const ZOD_URL = /^z\s*\.\s*url\s*\(/;
const ZOD_DATE = /^z\s*\.\s*(?:date|iso\s*\.\s*(?:date|datetime))\s*\(/;
const ZOD_NUMBER = /^z\s*\.\s*(?:number|int|coerce\s*\.\s*(?:number|int))\s*\(/;
const ZOD_BOOLEAN = /^z\s*\.\s*(?:boolean|coerce\s*\.\s*boolean)\s*\(/;
const ZOD_FILE = /^z\s*\.\s*file\s*\(/;
const ZOD_TUPLE = /^z\s*\.\s*tuple\s*\(/;
const ZOD_OBJECT = /^z\s*\.\s*object\s*\(/;

type ZodCall = { name: string; args: string; text: string };

/**
 * `z.string().min(1, "msg").max(3)` → the base `z.string()` and its trailing `.method(args)` calls.
 * The base is the *first* call (`z.string(…)`, `z.coerce.number(…)`, `z.iso.date(…)`), so
 * `z.coerce.number().min(0)` keeps `coerce` inside the base.
 */
function zodChain(expr: string): { base: string; calls: ZodCall[] } {
  let i = 0;
  while (i < expr.length && !/[A-Za-z0-9_$]/.test(expr[i])) i++;
  while (i < expr.length && /[A-Za-z0-9_$]/.test(expr[i])) i++;
  for (;;) {
    let j = i;
    while (j < expr.length && /\s/.test(expr[j])) j++;
    if (expr[j] !== ".") break;
    j++;
    while (j < expr.length && /\s/.test(expr[j])) j++;
    const nameAt = j;
    while (j < expr.length && /[A-Za-z0-9_$]/.test(expr[j])) j++;
    if (j === nameAt) break;
    let k = j;
    while (k < expr.length && /\s/.test(expr[k])) k++;
    if (expr[k] === "(") {
      const close = matchDelimiter(expr, k, "(", ")");
      // The base ends after its first parenthesised call.
      i = close < 0 ? expr.length : close + 1;
      break;
    }
    i = j; // `.coerce` / `.iso`: another segment before the call that ends the base
  }
  const calls: ZodCall[] = [];
  for (let at = i; at < expr.length; ) {
    while (at < expr.length && /\s/.test(expr[at])) at++;
    if (expr[at] !== ".") break;
    let j = at + 1;
    while (j < expr.length && /[A-Za-z0-9_$]/.test(expr[j])) j++;
    const name = expr.slice(at + 1, j);
    while (j < expr.length && /\s/.test(expr[j])) j++;
    if (expr[j] !== "(") break;
    const close = matchDelimiter(expr, j, "(", ")");
    if (close < 0) break;
    calls.push({ name, args: expr.slice(j + 1, close), text: expr.slice(at, close + 1) });
    at = close + 1;
  }
  return { base: expr.slice(0, i).trim(), calls };
}

/** The arguments inside the outermost `( … )` of an expression, or "". */
function outerArgs(text: string): string {
  const open = text.indexOf("(");
  const close = open < 0 ? -1 : matchDelimiter(text, open, "(", ")");
  return close < 0 ? "" : text.slice(open + 1, close);
}

/** The hand-written message in a call's arguments: a trailing string, or `{ error: "…" }`. */
function messageLiteral(args: string): string | undefined {
  const parts = splitEntries(args);
  const last = parts[parts.length - 1]?.trim();
  if (!last) return undefined;
  const bare = /^("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`)$/.exec(last);
  if (bare) return unescapeLiteral(bare[1]);
  const named = /(?:^|[,{]\s*)(?:error|message)\s*:\s*("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`)/.exec(last);
  return named ? unescapeLiteral(named[1]) : undefined;
}

/** The source of a `/…/flags` literal argument, for recognising the builder's own patterns. */
function regexSource(args: string): string | undefined {
  const m = /^\s*\/((?:\\.|[^/\\])*)\/[a-z]*/.exec(args);
  return m ? m[1] : undefined;
}

/** Bytes → megabytes, when that is a size the builder can express. */
function bytesToMb(bytes: number | undefined): number | undefined {
  if (bytes === undefined || bytes <= 0) return undefined;
  const size = Math.round((bytes / (1024 * 1024)) * 100) / 100;
  return size >= 0.1 && Math.round(size * 1024 * 1024) === bytes ? size : undefined;
}

/**
 * One `key: <expr>` entry → a field. What the builder has a shape for is read out;
 * every other call (`.refine(…)`, `.transform(…)`, a `.regex(…)` it does not know)
 * is kept verbatim in `customZod` — text, never executed here.
 */
function mapZodValue(key: string, expr: string, i: number, warnings: string[]): FieldSpec {
  const { base, calls } = zodChain(expr);
  const f: FieldSpec = { id: `imp_${i + 1}`, name: key, label: prettify(key), kind: "string", required: !ZOD_OPTIONAL_RE.test(expr) };
  const described = matchDescribe(expr);
  if (described) f.description = described;

  const used = new Set(["optional", "nullable", "describe"]);
  // `.or(z.literal(""))` is the builder's own "may be left empty", not custom code.
  if (calls.some((c) => c.name === "or" && /^\s*z\s*\.\s*literal\s*\(\s*(?:""|''|``)\s*\)\s*$/.test(c.args))) used.add("or");
  const messages: Record<string, string> = {};
  const note = (keyword: string, message: string | undefined) => {
    if (message) messages[keyword] = message;
  };
  const call = (name: string) => calls.find((c) => c.name === name);
  const numberArgOf = (name: string) => {
    const m = /^\s*(-?\d+(?:\.\d+)?)/.exec(call(name)?.args ?? "");
    return m ? Number(m[1]) : undefined;
  };

  const item = ZOD_ARRAY.test(base) ? outerArgs(base).trim() : "";
  const itemChain = item ? zodChain(item) : { base: "", calls: [] as ZodCall[] };
  const baseArg = outerArgs(base);

  if (item) {
    // Several of something: a list of options, or several files.
    if (ZOD_ENUM.test(itemChain.base)) {
      const options = zodEnumOptions(itemChain.base);
      if (options) {
        f.kind = "multi";
        f.options = options;
      } else {
        warnings.push(`${key}: a z.enum(…) without readable string options — used a text field.`);
      }
    } else if (ZOD_STRING.test(itemChain.base)) {
      f.kind = "multi";
    } else if (ZOD_FILE.test(itemChain.base)) {
      f.kind = "file";
      f.multiple = true;
      for (const c of itemChain.calls) if (c.name === "max") used.add("max");
      f.maxSizeMb = bytesToMb(Number(/^\s*(\d+)/.exec(itemChain.calls.find((c) => c.name === "max")?.args ?? "")?.[1]));
      note("maxLength", messageLiteral(itemChain.calls.find((c) => c.name === "max")?.args ?? ""));
    } else {
      warnings.push(`${key}: an array of something else — used a text field.`);
    }
    if (f.kind === "multi" || f.kind === "file") {
      used.add("min");
      note("minItems", messageLiteral(call("min")?.args ?? ""));
    }
  } else if (ZOD_ENUM.test(base)) {
    const options = zodEnumOptions(base);
    if (options) {
      f.kind = "enum";
      f.options = options;
    } else {
      warnings.push(`${key}: a z.enum(…) without readable string options — used a text field.`);
    }
    note("enum", messageLiteral(baseArg));
  } else if (ZOD_LITERAL.test(base)) {
    const literal = ZOD_LITERAL.exec(base);
    f.kind = "enum";
    if (literal) f.options = [unescapeLiteral(literal[1])];
  } else if (ZOD_STRING.test(base)) {
    if (call("email")) {
      used.add("email");
      f.format = "email";
      note("format", messageLiteral(call("email")?.args ?? ""));
    } else if (call("url")) {
      used.add("url");
      f.format = "url";
      note("format", messageLiteral(call("url")?.args ?? ""));
    }
    const time = calls.find((c) => c.name === "regex" && regexSource(c.args) === TIME_PATTERN);
    if (time) {
      used.add("regex");
      f.kind = "time";
      note("pattern", messageLiteral(time.args));
    } else if (!f.format) {
      used.add("min").add("max");
      // A required string is at least one character anyway, so `.min(1)` adds nothing.
      const min = numberArgOf("min");
      f.min = f.required && min === 1 ? undefined : min;
      f.max = numberArgOf("max");
      note("minLength", messageLiteral(call("min")?.args ?? ""));
      note("maxLength", messageLiteral(call("max")?.args ?? ""));
    }
  } else if (ZOD_EMAIL.test(base)) {
    f.format = "email";
    note("format", messageLiteral(baseArg));
  } else if (ZOD_URL.test(base)) {
    f.format = "url";
    note("format", messageLiteral(baseArg));
  } else if (ZOD_DATE.test(base)) {
    f.kind = "date";
    used.add("min").add("max"); // `.min()` on a date is a date bound the builder cannot hold
  } else if (ZOD_NUMBER.test(base)) {
    f.kind = "number";
    used.add("min").add("max");
    f.min = numberArgOf("min");
    f.max = numberArgOf("max");
    note("type", messageLiteral(baseArg));
    note("minimum", messageLiteral(call("min")?.args ?? ""));
    note("maximum", messageLiteral(call("max")?.args ?? ""));
  } else if (ZOD_BOOLEAN.test(base)) {
    f.kind = "boolean";
  } else if (ZOD_FILE.test(base)) {
    f.kind = "file";
    used.add("max");
    f.maxSizeMb = bytesToMb(Number(/^\s*(\d+)/.exec(call("max")?.args ?? "")?.[1]));
    note("type", messageLiteral(baseArg));
    note("maxLength", messageLiteral(call("max")?.args ?? ""));
  } else if (ZOD_TUPLE.test(base)) {
    f.kind = "range";
    const refine = call("refine");
    if (refine) {
      used.add("refine");
      // The builder's own bounds sit in the refine: `a >= min && b <= max && a <= b`.
      f.min = Number(/[\w\]]\s*>=\s*(-?\d+(?:\.\d+)?)/.exec(refine.args)?.[1]);
      f.max = Number(/[\w\]]\s*<=\s*(-?\d+(?:\.\d+)?)/.exec(refine.args)?.[1]);
      if (!Number.isFinite(f.min)) f.min = undefined;
      if (!Number.isFinite(f.max)) f.max = undefined;
      note("minimum", messageLiteral(refine.args));
    }
  } else if (ZOD_OBJECT.test(base) && /\bfrom\s*:/.test(baseArg) && /\bto\s*:/.test(baseArg)) {
    f.kind = "date-range";
  } else {
    warnings.push(`${key}: unsupported Zod type "${expr.replace(/\s+/g, " ").slice(0, 60)}" — used a text field.`);
  }

  const custom = [...calls, ...itemChain.calls].filter((c) => !used.has(c.name)).map((c) => c.text).join("");
  if (custom) f.customZod = custom;
  for (const [keyword, message] of Object.entries(messages)) {
    if (message !== defaultMessage(f, keyword)) f.errorMessage = { ...(f.errorMessage ?? {}), [keyword]: message };
  }
  return f;
}

export function parseZod(source: string): ImportResult {
  const warnings: string[] = [];
  const base = { format: "zod" as const, purpose: "", fields: [] as FieldSpec[], warnings };
  const src = stripComments(source);
  const objectAt = src.search(/z\s*\.\s*object\s*\(/);
  if (objectAt < 0) return { ...base, ok: false, warnings: [`No z.object({ … }) found. ${ZOD_HINT}`] };
  const braceAt = src.indexOf("{", src.indexOf("(", objectAt));
  if (braceAt < 0) return { ...base, ok: false, warnings: [`z.object( has no { … } body. ${ZOD_HINT}`] };
  const end = matchBrace(src, braceAt);
  if (end < 0) return { ...base, ok: false, warnings: ["Unbalanced braces in the z.object({ … }) body."] };

  const fields: FieldSpec[] = [];
  for (const entry of splitEntries(src.slice(braceAt + 1, end))) {
    const colon = indexOfTopLevel(entry, ":");
    const key = colon < 0 ? "" : entry.slice(0, colon).trim().replace(/^["'`]|["'`]$/g, "");
    if (!key) {
      warnings.push(`Skipped "${entry.replace(/\s+/g, " ").slice(0, 40)}": it is not a key: value pair.`);
      continue;
    }
    fields.push(normalizeField(mapZodValue(key, entry.slice(colon + 1).trim(), fields.length, warnings)));
  }
  if (!fields.length) warnings.push("No fields found in the object.");
  return { ...base, ok: fields.length > 0, purpose: matchDescribe(src.slice(end + 1)) ?? "", fields, warnings };
}

/* ------------------------------------------------------------------ entry points */

const emptyResult = (format: ImportFormat, message: string): ImportResult => ({ ok: false, format, purpose: "", fields: [], warnings: [message] });

/** A builder file: `{ schema, uiSchema }`. */
export function parseFormFile(source: string): ImportResult {
  let data: unknown;
  try {
    data = JSON.parse(source);
  } catch (e) {
    return emptyResult("builder-file", `Not valid JSON: ${(e as Error).message}`);
  }
  if (!isObj(data) || !isObj(data.schema)) return emptyResult("builder-file", 'Not a builder file: expected { "schema": { … }, "uiSchema": { … } }.');
  const r = readSchema(data.schema, isObj(data.uiSchema) ? data.uiSchema : {});
  return {
    ok: r.ok,
    format: "builder-file",
    purpose: r.purpose,
    fields: r.fields,
    threshold: r.threshold,
    overrides: r.overrides,
    warnings: r.warnings,
  };
}

/** Any JSON Schema object, with or without a uiSchema next to it. */
export function parseJsonSchema(source: string): ImportResult {
  let data: unknown;
  try {
    data = JSON.parse(source);
  } catch (e) {
    return emptyResult("json-schema", `Not valid JSON: ${(e as Error).message}`);
  }
  if (!isObj(data)) return emptyResult("json-schema", 'Expected a JSON object with a "properties" map.');
  const r = readSchema(data, {});
  return { ok: r.ok, format: "json-schema", purpose: r.purpose, fields: r.fields, threshold: r.threshold, overrides: r.overrides, warnings: r.warnings };
}

export function parseImport(source: string): ImportResult {
  const text = source.trim();
  if (!text) return emptyResult("json-schema", "Paste a schema or a Zod object first.");
  if (text.startsWith("{")) {
    try {
      const data: unknown = JSON.parse(text);
      if (isObj(data) && isObj(data.schema)) return parseFormFile(text);
    } catch {
      // Not JSON after all: the JSON Schema reader reports the syntax error.
    }
    return parseJsonSchema(text);
  }
  return parseZod(text);
}

/** The reader behind the hash and localStorage: a builder document → in-memory state. */
export function readFormDocument(data: unknown, warn: (message: string) => void = () => {}): SavedForm | null {
  if (!isObj(data) || !isObj(data.schema)) return null;
  const r = readSchema(data.schema, isObj(data.uiSchema) ? data.uiSchema : {});
  for (const message of r.warnings) warn(message);
  return r.ok ? { purpose: r.purpose, fields: r.fields, threshold: r.threshold ?? DEFAULT_THRESHOLD, overrides: r.overrides } : null;
}
